"""empty message

Revision ID: 0fedfaa6648f
Revises: 8b83f7730b33
Create Date: 2022-01-17 12:55:05.855687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fedfaa6648f'
down_revision = '8b83f7730b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_title_key', 'groups', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('groups_title_key', 'groups', ['title'])
    # ### end Alembic commands ###
