"""empty message

Revision ID: 8b83f7730b33
Revises: ca10feaf6ae2
Create Date: 2022-01-17 12:49:59.726324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b83f7730b33'
down_revision = 'ca10feaf6ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
