"""empty message

Revision ID: ca10feaf6ae2
Revises: db9036bf0308
Create Date: 2022-01-17 11:52:56.718848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca10feaf6ae2'
down_revision = 'db9036bf0308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
