"""empty message

Revision ID: db9036bf0308
Revises: 880ac91a8458
Create Date: 2022-01-15 05:51:32.373326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9036bf0308'
down_revision = '880ac91a8458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
