version:  "3.3"

services: 
    fastapi:
        build: ./docker/api
        container_name: "mahjong_fastapi_container"
        volumes: 
            - ./app:/usr/src/server/app
            - ./logs:/usr/src/logs/
            - ./scripts:/usr/src/scripts
        depends_on: 
            - db
        working_dir: /usr/src/scripts
        command: bash -c "./run.sh"
        # stdin_open: true
        ports: 
            - "8000:8000"
        networks: 
            - local-net
    
    db:
        build: ./docker/db
        container_name: "mahjong_db_container"
        restart: always
        tty: true
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mahjong_db_container
        volumes:
            - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
            - ./logs/db:/var/log/postgresql/
            - ./docker/db/data:/var/lib/postgresql/data/
        ports:
            - '5432:5432'
        networks: 
            - local-net
    
    nginx:
        build: ./docker/nginx
        container_name: mahjong_nginx_container
        depends_on:
            - fastapi
        ports:
            - "443:443"
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/ssh:/etc/nginx/ssl
            #- ./docker/certbot/www:/var/www/certbot
            # - ./docker/certbot/conf/:/etc/letsencrypt/
        #command: bash -c "etc/testssl/nginx_script.sh"
        networks:
            - local-net

networks:
    local-net:
        driver: bridge 